version: "3.8"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - servers
    depends_on:
      - server1
      - server2
      - server3
      - balancer

  balancer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["lb", "--trace=true"]
    networks:
      - servers

  server1:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["server", "--port=8080"]
    networks:
      - servers

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["server", "--port=8081"]
    networks:
      - servers

  server3:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["server", "--port=8082"]
    networks:
      - servers

networks:
  servers:
    driver: bridge